[build]
  command = "echo 'building...'"
  publish = "site"

[[redirects]]
    from = "/search"
    to = "https://www.google.com/"
    status = 200
    force = false
[[redirects]]
    from = "/search/*"
    to = "https://www.google.com/:splat"
    status = 200
    force = false
