[build]
  command = "echo 'building...'"
  publish = "site"

[[redirects]]
    from = "/*"
    to = "https://www.adartasoftware.com"
    status = 200
    force = false
[[redirects]]
    from = "/website"
    to = "https://www.adartasoftware.com"
    status = 200
    force = false
[[redirects]]
    from = "/website/*"
    to = "https://www.adartasoftware.com/:splat"
    status = 200
    force = false
